[package]
name = "reale-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenvy = { version = "0.15.0" }
reqwest = { version = "0.11.10" }
tokio = { version = "1", features = ["full"] }